server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
      routes:
        - id: ms-auth-route
          uri: ${URL_MS_AUTH:http://localhost:8085}
          predicates:
            - Path=/api/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCB
                fallbackUri: forward:/fallback/auth

        - id: ms-inventario-route
          uri: ${URL_MS_INVENTARIO:http://localhost:8081}
          predicates:
            - Path=/api/productos/**, /api/bodegas/**
          filters:
            - name: CircuitBreaker
              args:
                name: inventarioCB
                fallbackUri: forward:/fallback/inventario

        - id: ms-ventas-route
          uri: ${URL_MS_VENTAS:http://localhost:8083}
          predicates:
            - Path=/api/pedidos/**, /api/pagos/**
          filters:
            - name: CircuitBreaker
              args:
                name: ventasCB
                fallbackUri: forward:/fallback/ventas

        - id: ms-clientes-route
          uri: ${URL_MS_CLIENTES:http://localhost:8082}
          predicates:
            - Path=/api/clientes/**
          filters:
            - name: CircuitBreaker
              args:
                name: clientesCB
                fallbackUri: forward:/fallback/clientes

        - id: ms-logistica-route
          uri: ${URL_MS_LOGISTICA:http://localhost:8084}
          predicates:
            - Path=/api/despachos/**, /api/transportistas/**
          filters:
            - name: CircuitBreaker
              args:
                name: logisticaCB
                fallbackUri: forward:/fallback/logistica

springdoc:
  swagger-ui:
    urls:
      - name: MS Autenticacion
        url: /api/auth/v3/api-docs
      - name: MS Clientes
        url: /api/clientes/v3/api-docs
      - name: MS Inventario
        url: /api/productos/v3/api-docs
      - name: MS Ventas
        url: /api/pedidos/v3/api-docs
      - name: MS Logistica
        url: /api/despachos/v3/api-docs

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
    instances:
      authCB:
        baseConfig: default
      inventarioCB:
        baseConfig: default
      ventasCB:
        baseConfig: default
      clientesCB:
        baseConfig: default
      logisticaCB:
        baseConfig: default

logging:
  level:
    org.springframework.cloud.gateway: INFO