server:
  port: 8081

spring:
  application:
    name: ms-inventario
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_inventario_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /api/inventario/v3/api-docs

aws:
  s3:
    bucket-name: ${AWS_BUCKET_NAME:tu-bucket}
  access-key-id: ${AWS_ACCESS_KEY_ID:tu-access}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:tu-secret}
  session-token: ${AWS_SESSION_TOKEN:tu-token-temporal}
  region: ${AWS_REGION:us-east-1}