server:
  port: 8084

spring:
  application:
    name: ms-logistica
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_logistica_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  api-docs:
    path: /api/despachos/v3/api-docs