server:
  port: 8083

spring:
  application:
    name: ms-ventas
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_ventas_db
    username: postgres
    password: Kevin2209.
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect